# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quotes.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
