# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='added_by',
        ),
    ]
